// Generated by CoffeeScript 1.12.5
module.exports = {

  /*
  convert string to string array.
  e.g.
  `hello\nworld` -> `['hello\n', 'world']`
  `hello\nworld\n` -> `['hello\n', 'world\n']`
   */
  textToRows: function(text) {
    var texts;
    if (!text) {
      return '';
    }
    texts = text.split('\n').map(function(i) {
      return i.concat('\n');
    });
    if (text.endsWith('\n')) {
      texts = texts.slice(0, -1);
    } else if (texts.length > 0) {
      texts[texts.length - 1] = texts[texts.length - 1].slice(0, -1);
    }
    return texts;
  }
};
